import NavBar from "./components/NavBar";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="flex flex-col items-center justify-center h-[calc(100vh-64px)]">
          {children}
        </main>
      </body>
    </html>
  );
}
